3ds: add wslay and nettle
devkitPro/pacman-packages pull request #236
Opened 2021-06-17 21:27 UTC by Pixel-Pop

Here is a working example program, adapted from wslay's examples, with the 3ds connecting to a websocat server: [wslay-client.zip](https://github.com/devkitPro/pacman-packages/files/6673296/wslay-client.zip)

`gcc` is in nettle's `makedepends` because it seems nettle needs to build utilities to run on the build system at build time.

Please feel free to make any changes.

2021-06-18 13:03 UTC, WinterMute requested changes

2021-06-18 13:03 UTC, WinterMute commented on 3ds/nettle/PKGBUILD
> +pkgname=3ds-nettle
Just remove the nettle package, it's not necessary for the wslay library. It's only used for examples which won't be built if nettle isn't installed.

2021-06-18 13:03 UTC, WinterMute commented on 3ds/wslay/PKGBUILD
> +makedepends=('3ds-pkg-config' 'devkitpro-pkgbuild-helpers')
devkitpro-pkgbuild-helpers has been superceded by dkp-toolchain-vars and several other packages that aren't needed for this library. Just use dkp-toolchain-vars here.

2021-06-18 14:26 UTC, WinterMute commented
Don't worry about merging upstream into your fork when doing PRs, this can end up causing conflicts. If nothing you're editing has changed then you can just ignore it, otherwise it's better to rebase from upstream instead.

2021-06-19 00:02 UTC, Pixel-Pop commented
Thank you for your feedback. Should I open a separate PR for nettle?

2021-06-19 00:51 UTC, WinterMute approved these changes

2021-06-19 00:52 UTC, merged

2021-06-19 17:27 UTC, WinterMute commented
> Thank you for your feedback. Should I open a separate PR for nettle?

Thanks for making the changes so quickly. I've merged and packaged this now. 

I'm not sure nettle is really a good fit for 3DS unless there's something specific you're using it for that can't be done with mbedtls for instance. If nettle is added though then this package will need modding to avoid building examples.